[package]
name = "ptyd"
version = "0.1.0"
edition = "2021"

[dependencies]
libredox = "0.1.2"
redox-daemon = "0.1.2"
redox-scheme = "0.2.0"
redox_event = "0.4.0"
redox_syscall = "0.5.0"
redox_termios = "0.1.3"
